on:
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.2.3"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
